changelog:
  exclude:
    labels:
      - ignore-for-release
      - duplicate
      - invalid
    authors:
      - dependabot
  categories:
    - title: Breaking Changes
      labels:
        - Semver-Major
        - breaking-change
    - title: Features
      labels:
        - Semver-Minor
        - enhancement
        - feature
    - title: Fixes
      labels:
        - Semver-Patch
        - bug
        - fix
    - title: Documentation
      labels:
        - documentation
        - docs
    - title: Validation And CI
      labels:
        - ci
        - test
        - validation
    - title: Dependencies
      labels:
        - dependencies
    - title: Other Changes
      labels:
        - "*"
